defaults:
  return_address: 20.0.0.2/32
  src_pkt_address_range: 1.1.0.0/32
path_probing:
- head_end_rtr: r1
  ip_address: 10.0.0.1
  path:
  - hops:
    - 10.1.1.1
    - 10.1.1.5
    - 10.1.1.13
    name: r1-r2-r4-r6
    udp_port: 32768
  - hops:
    - 10.1.1.1
    - 10.1.1.7
    - 10.1.1.15
    name: r1-r2-r5-r6
    udp_port: 32769
  - hops:
    - 10.1.1.3
    - 10.1.1.11
    - 10.1.1.13
    name: r1-r3-r4-r6
    udp_port: 32770
  - hops:
    - 10.1.1.3
    - 10.1.1.9
    - 10.1.1.15
    name: r1-r3-r5-r6
    udp_port: 32771
